version: '3.8'

services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USERNAME}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"
